### ISSUE TITLE
断点拍摄视频时候，如果录制视频段超过7个将会报错，求解决方法。。（bug）

### ISSUE THREAD

**Issue by wangruoyu0324** [pili-engineering/PLDroidShortVideo#15]
E/AndroidRuntime: FATAL EXCEPTION: SurfaceRenderer
                                                           Process: com.aicheng, PID: 14641
                                                           java.lang.RuntimeException: eglCreateContext: EGL error: 0x3003
                                                               at com.qiniu.pili.droid.shortvideo.e.a.b.a(Egl14.java:214)
                                                               at com.qiniu.pili.droid.shortvideo.e.a.b.<init>(Egl14.java:62)
                                                               at com.qiniu.pili.droid.shortvideo.e.a.d.<init>(EglCore.java:27)
                                                               at com.qiniu.pili.droid.shortvideo.e.b.c.run(SurfaceRenderer.java:127)
                                                               at java.lang.Thread.run(Thread.java:818)

**Comment by Jhuster** [comment]
@wangruoyu0324 能否给出一份完整的 LOG

**Comment by wangruoyu0324** [comment]
@Jhuster 已发

**Comment by geeklok** [comment]
@wangruoyu0324 你测试的机型，系统版本时多少？是必现 7+ 片段会崩溃？录制时崩溃还是点击下一步时崩溃？有在别的机器测试过吗？

**Comment by geeklok** [comment]
@wangruoyu0324 你测试的机型，系统版本时多少？是必现 7+ 片段会崩溃？录制时崩溃还是点击下一步时崩溃？有在别的机器测试过吗？

**Comment by wangruoyu0324** [comment]
@Jhuster 不好意思昨天说错了，小米手机上没有出现7段视频限制，目前就我自己的手机努比亚 N510J出现这个情况。

**Comment by wangruoyu0324** [comment]
@Jhuster 你好，之前说的拍摄7段的问题，你们那边能解决么？努比亚N510J 这款手机。另外拼接视频段提示errorcode =8是什么意思啊？？

**Comment by wangruoyu0324** [comment]
@geeklok  你好，之前说的拍摄7段的问题，你们那边能解决么？努比亚N510J 这款手机。另外拼接视频段提示errorcode =8是什么意思啊？？

**Comment by Jhuster** [comment]
@wangruoyu0324 本短视频需要参考首页 README 联系商务授权，errorcode = 8 是未授权的意思

**Comment by junge89221** [comment]
@Jhuster 在拍摄最小时间如果超过7段，就会报错，必现~
com.qiniu.pili.droid.shortvideo.b.f.g(SectionManager.java:279)

java.lang.IllegalArgumentException
                                                                          at android.media.MediaExtractor.selectTrack(Native Method)
                                                                          at com.qiniu.pili.droid.shortvideo.b.f.g(SectionManager.java:279)
                                                                          at com.qiniu.pili.droid.shortvideo.b.f$1.run(SectionManager.java:240)
                                                                          at java.lang.Thread.run(Thread.java:818)
