### ISSUE TITLE
视频录制sdk，调用concatSections报错

### ISSUE THREAD

**Issue by whaoming** [pili-engineering/PLDroidShortVideo#23]
只出现下面信息：
java.lang.IllegalArgumentException
at android.media.MediaExtractor.selectTrack(Native Method)
at com.qiniu.pili.droid.shortvideo.b.e.g(SectionManager.java:274)
at com.qiniu.pili.droid.shortvideo.b.e$1.run(SectionManager.java:236)
at java.lang.Thread.run(Thread.java:761)

**Comment by geeklok** [comment]
是必现吗，详细操作流程可以说一下，还有是什么机型，系统版本？

**Comment by Jhuster** [comment]
https://github.com/pili-engineering/PLDroidShortVideo/issues/27
