### ISSUE TITLE
 在拍摄最小时间内如果超过7段，在拼接视频的时候 就会报错！

### ISSUE THREAD

**Issue by junge89221** [pili-engineering/PLDroidShortVideo#27]
@Jhuster 在拍摄最小时间如果超过7段，就会报错，必现~所以手机都出现了··
com.qiniu.pili.droid.shortvideo.b.f.g(SectionManager.java:279)

java.lang.IllegalArgumentException
at android.media.MediaExtractor.selectTrack(Native Method)
at com.qiniu.pili.droid.shortvideo.b.f.g(SectionManager.java:279)
at com.qiniu.pili.droid.shortvideo.b.f$1.run(SectionManager.java:240)
at java.lang.Thread.run(Thread.java:818)

**Comment by Johnny1994** [comment]
好的，谢谢反馈，我们这边验证后会着手修复的
