### ISSUE TITLE
保存缩略图出错

### ISSUE THREAD

**Issue by 919317632** [pili-engineering/PLDroidShortVideo#39]
错误内容如下：

java.lang.IllegalArgumentException
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:71)
	at com.view.videorecorder.activity.VideoRecorderActivity.saveVideoThumb(VideoRecorderActivity.java:404)
	at com.view.videorecorder.activity.VideoRecorderActivity.access$1400(VideoRecorderActivity.java:68)
	at com.view.videorecorder.activity.VideoRecorderActivity$4$1.run(VideoRecorderActivity.java:357)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6434)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)

**Comment by Jhuster** [comment]
@919317632 setDataSource 的 URL 内容是什么

**Comment by 919317632** [comment]
统计到的错误，应该是本地视频地址，具体地址是安卓系统的文件地址，大部分手机没问题，这应该是兼容性问题

**Comment by Jhuster** [comment]
嗯，麻烦给到具体的机型，我们复现下

**Comment by 919317632** [comment]
魅族1s，很少见的机型……
