### ISSUE TITLE
vivo x6,vivo  y67使用裁剪，压缩报错

### ISSUE THREAD

**Issue by mrme2014** [pili-engineering/PLDroidShortVideo#46]
运行demo项目，在vivox6,y64手机上裁剪，转码Mov格式视频，进度到99%时报错，error  code  8

**Comment by mrme2014** [comment]
下面是完整报错信息，希望能够解决一下。谢谢。


{SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@a79c60f, versionCode=1, BOARD=unknown, BOOTLOADER=unknown, TYPE=user, ID=MRA58K, TIME=1504359724000, BRAND=vivo, TAG=Build, SERIAL=FIW8SSLZ99999999, HARDWARE=mt6755, SUPPORTED_ABIS=[Ljava.lang.String;@ecc169c, CPU_ABI=armeabi-v7a, RADIO=unknown, IS_DEBUGGABLE=false, MANUFACTURER=vivo, STACK_TRACE=java.lang.IllegalArgumentException 	at android.media.MediaExtractor.readSampleData(Native Method) 	at com.qiniu.pili.droid.shortvideo.b.l.a(ShortVideoTranscoderCore.java:265) 	at com.qiniu.pili.droid.shortvideo.b.l.b(ShortVideoTranscoderCore.java:110) 	at com.qiniu.pili.droid.shortvideo.b.l.d(ShortVideoTranscoderCore.java:31) 	at com.qiniu.pili.droid.shortvideo.b.l$1.b_(ShortVideoTranscoderCore.java:340) 	at com.qiniu.pili.droid.shortvideo.d.d.b_(HWVideoEncoder.java:118) 	at com.qiniu.pili.droid.shortvideo.d.c.m(HWEncoderBase.java:167) 	at com.qiniu.pili.droid.shortvideo.d.c.run(HWEncoderBase.java:242) 	at java.lang.Thread.run(Thread.java:818) , SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@a298f6e, TAGS=release-keys, CPU_ABI2=armeabi, UNKNOWN=unknown, USER=compiler, FINGERPRINT=vivo/PD1612/PD1612:6.0/MRA58K/1504359241:user/release-keys, HOST=compiler026, PRODUCT=PD1612, versionName=1.0, DISPLAY=MRA58K release-keys, MODEL=vivo Y67, DEVICE=PD1612}

**Comment by Jhuster** [comment]
@mrme2014 不支持 mov 格式的视频文件
