### ISSUE TITLE
1.7.0视频转码崩溃

### ISSUE THREAD

**Issue by mayz6732** [pili-engineering/PLDroidShortVideo#53]
1.7.0demo视频转码在华为荣耀 6 plus上崩溃,每次必显,其他手机没问题
![Uploading 1513671481(1).jpg…]()

**Comment by mayz6732** [comment]
12-19 16:22:28.160 4414-4642/? E/SubmitMessage: Submit string: submit:trigger=0,bugtype=2,modulename=com.qiniu.pili.droid.shortvideo.demo,level=1,testtype=NORMAL,path=/data/log/unzip/PE-TL10_V100R001CHNC00B260_T8D0215111001162_20171219162228_crash
12-19 16:22:28.235 4414-4633/? E/PackageLogInfoManager: checkPackageLogState, cr: android.app.ContextImpl$ApplicationContentResolver@431c49a8, packageNames: null
12-19 16:22:28.625 8146-8146/? E/WindowManager: android.view.WindowLeaked: Activity com.qiniu.pili.droid.shortvideo.demo.activity.VideoTranscodeActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{43345298 V.E..... R.....I. 0,0-1026,421} that was originally added here
                                                    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:391)
                                                    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:258)
                                                    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                    at android.app.Dialog.show(Dialog.java:323)
                                                    at com.qiniu.pili.droid.shortvideo.demo.activity.VideoTranscodeActivity.doTranscode(VideoTranscodeActivity.java:158)
                                                    at com.qiniu.pili.droid.shortvideo.demo.activity.VideoTranscodeActivity.onClickTranscode(VideoTranscodeActivity.java:141)
                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                    at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
                                                    at android.view.View.performClick(View.java:4446)
                                                    at android.view.View$PerformClick.run(View.java:18480)
                                                    at android.os.Handler.handleCallback(Handler.java:733)
                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                    at android.os.Looper.loop(Looper.java:136)
                                                    at android.app.ActivityThread.main(ActivityThread.java:5315)
                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by geeklok** [comment]
这个貌似不是真正的 crash log，我们先验证一下，如果有需要请再抓一份 log，谢谢你的反馈。

**Comment by KevinHuo** [comment]
1.8.0 应该已经修复，您可以试下。再次感谢您的反馈！
