### ISSUE TITLE
导入Demo 视频拍摄App重启

### ISSUE THREAD

**Issue by xinlc** [pili-engineering/PLDroidShortVideo#56]
导入PLDroidShortVideo-1.8.0 Demo 为Library，录制视频报错并重启App。
错误log：

01-10 15:31:51.058 18848-18848/bobaikeji.cyq W/System.err: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
01-10 15:31:51.068 18848-18848/bobaikeji.cyq E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: bobaikeji.cyq, PID: 18848
                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{bobaikeji.cyq/com.qiniu.pili.droid.shortvideo.demo.activity.VideoRecordActivity}: android.view.InflateException: Binary XML file line #243: Error inflating class com.kiwi.ui.widget.KwControlView
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
                                                                   at android.app.ActivityThread.access$900(ActivityThread.java:175)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5418)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                Caused by: android.view.InflateException: Binary XML file line #243: Error inflating class com.kiwi.ui.widget.KwControlView
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:802)
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:851)
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:510)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:420)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:371)
                                                                   at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:412)
                                                                   at android.app.Activity.setContentView(Activity.java:2180)
                                                                   at com.qiniu.pili.droid.shortvideo.demo.activity.VideoRecordActivity.onCreate(VideoRecordActivity.java:112)
                                                                   at android.app.Activity.performCreate(Activity.java:6083)
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466) 
                                                                   at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:135) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5418) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
                                                                Caused by: java.lang.ClassNotFoundException: Didn't find class "com.kiwi.ui.widget.KwControlView" on path: DexPathList[[zip file "/data/app/bobaikeji.cyq-1/base.apk"],nativeLibraryDirectories=[/data/app/bobaikeji.cyq-1/lib/arm, /vendor/lib, /system/lib]]
                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:577)
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:851) 
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:854) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:510) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:420) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:371) 
                                                                   at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:412) 
                                                                   at android.app.Activity.setContentView(Activity.java:2180) 
                                                                   at com.qiniu.pili.droid.shortvideo.demo.activity.VideoRecordActivity.onCreate(VideoRecordActivity.java:112) 
                                                                   at android.app.Activity.performCreate(Activity.java:6083) 
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115) 
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357) 
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466) 
                                                                   at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:135) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5418) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
                                                               	Suppressed: java.lang.ClassNotFoundException: com.kiwi.ui.widget.KwControlView
                                                                   at java.lang.Class.classForName(Native Method)
                                                                   at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                   at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                   		... 24 more
                                                                Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by geeklok** [comment]
kiwi 的 module 有加上了吗

**Comment by xinlc** [comment]
@geeklok 依赖问题，已解决
